---
- include_vars: linuxgroups.yml
# tasks file for dev-server
- name: 'Install EPEL repo if CentOS 6/7'
  yum: name=epel-release state=latest
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: 'Enable Extras/Optional repo if RHEL 7'
  command: subscription-manager repos --enable={{ item }}
  with_items:
    - rhel-7-server-extras-rpms
    - rhel-7-server-optional-rpms
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'

- name: 'Install common pkgs across all applications'
  yum: name={{ item }} state=latest
  with_items:
    - vim
    - ntp
    - net-tools
    - sysstat
    - rsync
    - strace
    - screen
    - yum-utils
    - redhat-lsb
    - lsof
    - lftp
    - procmail
    - mutt
    - bzip2
    - zip
    - telnet

- name: "Install common pkgs for development"
  yum: state=present name={{ item }}
  with_items:
    - apr-util
    - gcc
    - gcc-c++
    - boost
    - boost-devel
    - boost-doc
    - cryptopp
    - cryptopp-devel
    - cryptopp-progs
    - uuid
    - uuid-c++
    - uuid-c++-devel
    - uuid-devel

- name: Install minimal X11 environment
  yum: name={{ item }} state=installed
  with_items:
    - xorg-x11-xauth
    - libXtst
    - libX11
    - libXau
    - libXdmcp
    - libICE
    - libXext
    - libXmu
    - libXt
    - libXp 
    - libfontenc
    - libXaw
    - libxkbfile
    - libXpm
    - xorg-x11-apps

- name: ensure that X11Forwarding is set in sshd_config  
  lineinfile: "line='X11Forwarding yes' dest=/etc/ssh/sshd_config regexp='^#X11Forwarding' state=present"
  notify:
  - restart sshd

- name: "Disable Selinux"
  selinux:
    state: disabled
- command: /usr/sbin/setenforce 0
  ignore_errors: yes

- name: 'Disable firewalld if enabled'
  service: name=firewalld state=stopped enabled=False

- name: Create groups for Developers
  group: name={{ item.groupname }} gid={{ item.gid }} state=present
  with_items: '{{linuxgroups}}'
