---
- name: 'Install Python PIP'
  yum:  name=python-pip state=latest 
  when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7') or
        (ansible_distribution == 'Red Hat Enterprise Linux' and ansible_distribution_major_version == '7')

- name: 'Install AWS CLI'
  yum:  name=awscli state=latest
  when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7') or
        (ansible_distribution == 'Red Hat Enterprise Linux' and ansible_distribution_major_version == '7')

- name: 'Install Python2.6'
  yum: name=python26 state=present
  when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '5') or
        (ansible_distribution == 'Red Hat Enterprise Linux' and ansible_distribution_major_version == '5')

- name: 'Dowload AWS-CLI zip file'
  get_url: url="https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" dest="/opt/awscli-bundle.zip"
  when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '5') or
        (ansible_distribution == 'Red Hat Enterprise Linux' and ansible_distribution_major_version == '5')

- name: 'Extract AWS-CLI zip file under opt '
  unarchive: copy=no src=/opt/awscli-bundle.zip dest=/opt creates=/opt/awscli-bundle
  when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '5') or
        (ansible_distribution == 'Red Hat Enterprise Linux' and ansible_distribution_major_version == '5')

- name: 'Install AWS-CLI...'
  command: /usr/bin/python2.6 /opt/awscli-bundle/install -i /usr/local/aws -b /usr/bin/aws
  when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '5') or
        (ansible_distribution == 'Red Hat Enterprise Linux' and ansible_distribution_major_version == '5')

- name: 'Create the AWS config directory'
  file: >
    path=~{{ aws_cli_user }}/.aws
    state=directory
    owner={{ aws_cli_user }}
    group={{ aws_cli_user }}
    mode=0755

- name: 'Copy AWS CLI config'
  template: >
    src=aws_cli_config.j2
    dest=~{{ aws_cli_user }}/.aws/config
    owner={{ aws_cli_user }}
    group={{ aws_cli_user }}
    mode=0644

- name: 'Copy AWS CLI credentials'
  template: >
    src=aws_cli_credentials.j2
    dest=~{{ aws_cli_user }}/.aws/credentials
    owner={{ aws_cli_user }}
    group={{ aws_cli_user }}
    mode=0644

- name: 'Copy over files '
  copy: src={{ item }}  dest=~{{ aws_cli_user }}/.aws/ owner=root group=root mode="u+rw,g-wx,o-rwx"
  with_items:
    - get-pip.py
    - samlapi.py

- name: 'Install requested Python pkgs'
  pip: name={{ item }}
  with_items:
    - boto
    - beautifulsoup4
    - requests-ntlm

