---
- name: Install minimal X11 environment
  yum: name={{ item }} state=installed
  with_items:
        - xorg-x11-xauth
        - libXtst
        - libX11
        - libXau
        - libXdmcp
        - libICE
        - libXext
        - libXmu
        - libXt
        - libXp 
        - libfontenc
        - libXaw
        - libxkbfile
        - libXpm
        - xorg-x11-apps

- name: ensure that X11Forwarding is set in sshd_config  
  lineinfile: "line='X11Forwarding yes' dest=/etc/ssh/sshd_config regexp='^#X11Forwarding' state=present"
  notify:
  - restart sshd
