---
- name: "Enable PostgreSQL 9.5 from PGDG"
  yum:
    name: "{{ rhel_pgdg_repo_rpm_url }}"
    state: present
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'

- name: "Enable PostgreSQL 9.5 from PGDG"
  yum:
    name: "{{ centos_pgdg_repo_rpm_url  }}"
    state: present
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: "Install PostgreSQL server packages"
  with_items:
    - "check_postgres"
    - "postgresql95-contrib"
    - "postgresql95-server"
  yum:
    name: "{{ item }}"
    state: present

- name: "Install PostgreSQL client packages"
  with_items:
    - "postgresql95"
    - "postgresql95-libs"
  yum:
    name: "{{ item }}"
    state: present

- name: "Fix missing pg_config"
  alternatives:
    name: "pgsql-pg_config"
    path: "/usr/pgsql-9.5/bin/pg_config"
    link: "/usr/bin/pg_config"

# create a directory if it doesn't exist
- file:
    path: /data
    state: directory
    mode: 0755
    owner: postgres
    group: postgres

- name: "Has database been initialized?"
  register: initdb
  command: "{{ '/usr/pgsql-9.5/bin/postgresql95-check-db-dir ' ~ pg_data_dir }}"
  ignore_errors: true
  always_run: true

- name: "Initialize database"
  when: initdb|failed
  command: "sudo -u postgres /usr/pgsql-9.5/bin/initdb -d /data"

- name: "Adjust PostgreSQL configuration"
  with_items:
    - "pg_hba.conf"
    - "pg_ident.conf"
    - "postgresql.conf"
  copy:
    dest: "{{ pg_data_dir ~ '/' ~ item }}"
    src: "{{ item }}"
    owner: "postgres"
    group: "postgres"
    mode: "0600"
  notify:
    - "Restart postgresql-9.5 service"

- name: "Enable PostgreSQL service"
  service:
    name: "postgresql-9.5"
    state: started
    enabled: yes
