---
- hosts: all
  remote_user: ansibleitamdevops
  become: true
#  remote_user: ec2-user
  become_method: sudo
  become_user: root

  roles:
    - user_dev
    - gcc
    - X11
#    - java
    - dev-pkgs  
 #   - postgres95 
